name: Update dependencies and Build

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH key and passphrase
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Start SSH agent and add the key with passphrase
          eval "$(ssh-agent -s)"
          ssh-add - <<< "Mansueito4316!"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
