# name: Update dependencies and Build

# on:
#   schedule:
#     - cron: "*/2 * * * *"

# jobs:
#   update_and_build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2

#       - name: Add SSH private key
#         uses: webfactory/ssh-agent@v0.4.1
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Install dependencies and build
#         run: |
#           npm install
#           npm run build

name: Update Library and Build Projects

on:
  push:
    branches:
      - main
    paths:
      - 'src/components/**'
  repository_dispatch:
    types: [update]

jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update library to the latest version
        id: update_library
        run: |
          npm update @dvdcpp/comp-lib
          echo "::set-output name=library-updated::true"

      - name: Build component library
        run: npm run build

      - name: Update and build React projects
        if: steps.update_library.outputs.library-updated == 'true'
        run: |
          npm install @dvdcpp/comp-lib@latest
          for dir in ./src/components/*/; do
            cd $dir
            npm install
            npm run build
            cd ../../..
          done
