name: Update dependencies and Build

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
